AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: Provide the stage of the project

  ProjectName:
    Type: String
    Description: Provide the name of the project
  
  BucketName:
    Type: String
    Description: Provide the name of the bucket to store the artifacts

Resources:
  SeriesSSMParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${ProjectName}-${Environment}-series-list
      Description: Series Names and ids
      Tier: Standard
      Type: String
      Value: To be filled later
      Tags: 
        Project: !Ref ProjectName

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
      LifecycleConfiguration: 
        Rules:
          - ExpirationInDays: 7
            Status: Enabled
      Tags: 
        - Key: Project
          Value: !Ref ProjectName

