AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Email:
    Type: String
    Description: Provide the email that the updates will be send to 

Resources:
  AirdateLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Description: String
      Environment:
        Variables: 
          BASE_URL : http://api.tvmaze.com
          SRC_EMAIL : !Ref Email
          DST_EMAIL : !Ref Email
          SERIES_LIST : To be filled later
          IDS_LIST : To be filled later
      Events:
        CloudwatchEvent:
          Type: Schedule
          Properties:
            Name: series-airdate-weekly-update
            Description: Weekly Lambda Trigger
            Schedule: cron(0 10 ? * FRI *)
            Enabled: True
      FunctionName: airdate-update-function
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Policies:
        #- AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Runtime: python3.7
      Timeout: 3