AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  ProjectName:
    Type: String
    Description: Provide the name of the project
    Default: series-airdate-updater
  
  Email:
    Type: String
    Description: Provide the email that the updates will be send to 

Resources:
  AirdateLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Description: Lambda Function to provide updates on the series upcoming airdates
      Environment:
        Variables: 
          BASE_URL : http://api.tvmaze.com
          SRC_EMAIL : !Ref Email
          DST_EMAIL : !Ref Email
          NAMES_SSM_NAME : !Sub ${ProjectName}-name-list
          IDS_SSM_NAME : !Sub ${ProjectName}-ids-list
      Events:
        CloudwatchEvent:
          Type: Schedule
          Properties:
            Name: !Sub ${ProjectName}-weekly
            Description: Weekly Lambda Trigger
            Schedule: cron(0 10 ? * FRI *)
            Enabled: True
      FunctionName: !Sub ${ProjectName}-function
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ssm:GetParameter
              Resource: '*'
      Runtime: python3.7
      Timeout: 3